version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - src/.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtual-wallet-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
