name: Virtual Wallet

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 